Fix all GCC 6+ warnings
Squashed commit of the following:

commit 6effa57b9a4d0acaa818068607068dd7b5c3b367
Author: Albert I <krascgq@outlook.co.id>
Date: Wed Dec 6 23:02:24 2017 +0800
Changes to be committed:

    staging: prima: GTFO switch-unreachable warning#

    Change-Id: Ic8b4e35389bc91f9b539c31de1da252d43f347cd
    Signed-off-by: Albert I <krascgq@outlook.co.id>

commit 6db0d8e776b821717c8d7e0eab0dfbddf0a100df
Author: Albert I <krascgq@outlook.co.id>
Date: Wed Dec 6 22:47:00 2017 +0800

    msm: ipa: Address memset-elt-size warning

    Change-Id: Ic9903a4f0a60e3f4c31e8254883a9dd01632cfd7
    Signed-off-by: Albert I <krascgq@outlook.co.id>

commit 5591e95682ec15ea4d7b726d82acc693f6a3eca1
Author: Albert I <krascgq@outlook.co.id>
Date: Sat Sep 16 22:31:08 2017 +0800

    ASoC: msm: Kill memset-transposed-args warning

    Change-Id: Iaccb14b2a438ab43d8b79222501e7cafaa2f0d26
    Signed-off-by: Albert I <krascgq@outlook.co.id>
commit 82672baddf3475b5e0f605996a3c55b61257b81d
Author: Albert I <krascgq@outlook.co.id>
Date: Tue May 9 21:20:22 2017 +0800

    msm: camera_v2: msm.c: Fix bool-compare warning

    Break the chain to fix the warning.
    Reference: http://stackoverflow.com/a/30807984

    Change-Id: I9e5dee699121fdda4685bb5ab8badd9645939d59
    Signed-off-by: Albert I <krascgq@outlook.co.id>

commit fe597a90070f6adddc84bec1c040025f02652c96
Author: Albert I <krascgq@outlook.co.id>
Date: Tue May 9 21:03:05 2017 +0800

    drivers: Fix logical-not-parentheses warnings

    For video/msm/mdss/mdss_mdp_pp.c also fix bool-compare warning.
    Updated. Reference: http://stackoverflow.com/a/30556379

    Change-Id: Iaae964bebd105b0089d3a9d159c65e35fd5915b2
    Signed-off-by: Albert I <krascgq@outlook.co.id>

commit 214dadd72f17aef55f4ca87321ad7dc5b1edad6d
Author: Albert I <krascgq@outlook.co.id>
Date: Tue May 9 21:48:47 2017 +0800

    kernel: Fix discarded-array-qualifiers warnings

    Change-Id: I1dcf6968c1f854cf959654df2f27ca75b2741bbf
    Signed-off-by: Albert I <krascgq@outlook.co.id>

commit 9b7e608a462cd684f68f396c94b5bbc72cc51dd9
Author: Albert I <krascgq@outlook.co.id>
Date: Fri Mar 3 07:52:05 2017 +0800

    staging: prima: Ensure compatibility with GCC6

    Fixes:
    drivers/staging/prima/CORE/VOSS/src/wlan_nv_template_builtin.c:590:10: error:
initializer element is not computable at load time
              (((char *)&(nvDefaults.tables.hwCalValues.calData.psSlpTimeOvrHdxLNA5G) +
              ^
    drivers/staging/prima/CORE/VOSS/src/wlan_nv_template_builtin.c:590:10: note: (near
initialization for 'NvTablesBuiltIn[4][3].offset')
    make[3]: *** [drivers/staging/prima/CORE/VOSS/src/wlan_nv_template_builtin.o] Error 1
    scripts/Makefile.build:308: recipe for target
'drivers/staging/prima/CORE/VOSS/src/wlan_nv_template_builtin.o' failed

    Change-Id: Iec8a458514dab32466932e9c6197ef2f87c97d6b
    Signed-off-by: Albert I <krascgq@outlook.co.id>

commit bd0dbd237352859ef8be1def98a5ea57fb9bacea
Author: Albert I <krascgq@outlook.co.id>
Date: Sun May 7 23:44:48 2017 +0800
    kernel: Eliminate misleading-indentation warnings

    Stop spamming my logs!
    Move positions of several codes just to prevent these warnings.
    PS: Disable warnings instead for prima as codes are poorly managed.

    Change-Id: I269ad292a748e98db96bba0afba13d32997519e9
    Signed-off-by: Albert I <krascgq@outlook.co.id>

Change-Id: Ie0ab3a6ab0169fdc53c85579a747c91552aafdca
Signed-off-by: Ravi Pingat <pingatravi@gmail.com>